worker_processes 1;
error_log /var/log/nginx/error.log warn;
events { worker_connections 1024; }

stream {
    map $ssl_preread_server_name $backend {
        ~^(api\.|chat\.|swoop\.|tech\.|www\.)?autoro\.tech$  127.0.0.1:9443;
        ~^(www\.)?pquoc\.com$                                127.0.0.1:9443;
        default                                              127.0.0.1:10443;
    }
    server {
        listen 443;
        proxy_pass $backend;
        proxy_protocol off;
        ssl_preread on;
        proxy_connect_timeout 10s;
        proxy_timeout 24h;
    }
}
