-- Spot tracking + Telegram conversion pipeline (Meta CAPI)
-- Run on Supabase/PostgreSQL.

create extension if not exists pgcrypto;

create table if not exists public.spots (
  id bigint generated by default as identity primary key,
  name text not null,
  target_tg_url text not null,
  fb_pixel_id text not null,
  fb_capi_token text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.landings (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  page_url text not null,
  spot_id bigint not null references public.spots(id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.clicks (
  click_id uuid primary key default gen_random_uuid(),
  spot_id bigint not null references public.spots(id) on delete cascade,
  fbclid text,
  ip_address text,
  user_agent text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  created_at timestamptz not null default now()
);

create table if not exists public.conversions (
  id bigint generated by default as identity primary key,
  click_id uuid not null references public.clicks(click_id) on delete cascade,
  event_name text not null default 'Lead',
  status text not null default 'pending' check (status in ('pending', 'success', 'failed')),
  fb_event_id text,
  created_at timestamptz not null default now()
);

create index if not exists idx_clicks_spot_id_created_at on public.clicks (spot_id, created_at desc);
create index if not exists idx_clicks_fbclid on public.clicks (fbclid);
create index if not exists idx_conversions_click_id on public.conversions (click_id);
create index if not exists idx_conversions_status_created_at on public.conversions (status, created_at desc);
create index if not exists idx_landings_spot_id on public.landings (spot_id);
create index if not exists idx_landings_is_active on public.landings (is_active);

alter table public.conversions add column if not exists error_message text;
alter table public.conversions add column if not exists meta_response jsonb;
alter table public.conversions add column if not exists retried_from_conversion_id bigint references public.conversions(id);

-- Helpful read model for dashboard.
create or replace view public.spot_stats as
select
  s.id as spot_id,
  s.name,
  count(distinct c.click_id) as clicks_count,
  count(*) filter (where v.status = 'success') as successful_conversions_count
from public.spots s
left join public.clicks c on c.spot_id = s.id
left join public.conversions v on v.click_id = c.click_id
group by s.id, s.name;

-- Detailed postback log for admin observability.
create or replace view public.spot_postback_log_v as
select
  v.id as conversion_id,
  v.click_id,
  c.spot_id,
  s.name as spot_name,
  v.event_name,
  v.status,
  v.fb_event_id,
  v.error_message,
  v.created_at as conversion_created_at
from public.conversions v
join public.clicks c on c.click_id = v.click_id
join public.spots s on s.id = c.spot_id;

-- Daily metrics (base view).
create or replace view public.spot_metrics_daily_v as
select
  s.id as spot_id,
  s.name as spot_name,
  date_trunc('day', c.created_at)::date as day,
  count(distinct c.click_id) as clicks_count,
  count(*) filter (where v.status = 'success') as successful_conversions_count,
  count(*) filter (where v.status = 'failed') as failed_conversions_count,
  case
    when count(distinct c.click_id) = 0 then 0
    else round(
      (count(*) filter (where v.status = 'success'))::numeric
      / count(distinct c.click_id)::numeric * 100,
      2
    )
  end as conversion_rate
from public.spots s
left join public.clicks c on c.spot_id = s.id
left join public.conversions v on v.click_id = c.click_id
group by s.id, s.name, date_trunc('day', c.created_at)::date;

-- Materialized view for fast analytics dashboard reads.
create materialized view if not exists public.spot_metrics_mv as
select * from public.spot_metrics_daily_v;

create unique index if not exists idx_spot_metrics_mv_uq
  on public.spot_metrics_mv (spot_id, day);

create index if not exists idx_spot_metrics_mv_day
  on public.spot_metrics_mv (day desc);

create or replace function public.refresh_spot_metrics_mv()
returns void
language plpgsql
as $$
begin
  refresh materialized view public.spot_metrics_mv;
end;
$$;

-- Retry queue for n8n processor (admin-triggered retries).
create table if not exists public.postback_retry_queue (
  id bigint generated by default as identity primary key,
  conversion_id bigint not null references public.conversions(id) on delete cascade,
  click_id uuid not null references public.clicks(click_id) on delete cascade,
  spot_id bigint not null references public.spots(id) on delete cascade,
  reason text not null default 'manual_retry',
  status text not null default 'pending' check (status in ('pending', 'processing', 'success', 'failed', 'cancelled')),
  n8n_execution_id text,
  error_message text,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists idx_postback_retry_queue_status_created_at
  on public.postback_retry_queue (status, created_at desc);

create index if not exists idx_postback_retry_queue_conversion_id
  on public.postback_retry_queue (conversion_id);
